apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: greeting-service
  name: greeting-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting-service
  template:
    metadata:
      labels:
        app: greeting-service
    spec:
      containers:
        - image: greeting-service:0.0.1
          imagePullPolicy: IfNotPresent
          name: greeting-service

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: greeting-service
  name: greeting-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: greeting-service
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greeting-service-ingress
  labels:
    app: greeting-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: greeting-service.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: greeting-service
            port:
              number: 80
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: greeting-service
            port:
              number: 80