apiVersion: v1
kind: Pod
metadata:
  name: hello-api
  labels:
    app: hello-api
    version: "0.0.1"
    type: api
spec:
  containers:
    - name: hello-api
      image: hello-api:0.0.1
      ports:
      - containerPort: 3000